export const OFFLINE_VENDORS = [
  { id: 'auto', name: 'Auto-detect platform (recommended)' },
  { id: 'cisco_ios', name: 'Cisco IOS' },
  { id: 'cisco_iosxe', name: 'Cisco IOS-XE' },
  { id: 'cisco_nxos', name: 'Cisco NX-OS / Nexus' },
  { id: 'cisco_asa', name: 'Cisco ASA' },
  { id: 'arista_eos', name: 'Arista EOS' },
  { id: 'juniper_junos', name: 'Juniper Junos' },
  { id: 'aruba_aoscx', name: 'Aruba AOS-CX' },
  { id: 'aruba_aos', name: 'Aruba AOS-Switch / ProCurve' },
  { id: 'hpe_comware', name: 'HPE Comware' },
  { id: 'extreme_exos', name: 'ExtremeXOS' },
  { id: 'extreme_voss', name: 'Extreme VOSS' },
  { id: 'brocade_fastiron', name: 'Brocade / Ruckus FastIron / ICX' },
  { id: 'dell_os10', name: 'Dell OS10' },
  { id: 'dell_os9', name: 'Dell OS9 / FTOS' },
  { id: 'mikrotik_routeros', name: 'MikroTik RouterOS' },
  { id: 'vyos', name: 'VyOS' },
  { id: 'fortios', name: 'Fortinet FortiOS' },
  { id: 'paloalto_panos', name: 'Palo Alto PAN-OS' },
  { id: 'sonic', name: 'SONiC' },
  { id: 'linux_frr', name: 'FRRouting / Linux routing' },
  { id: 'ubiquiti_edgeos', name: 'Ubiquiti EdgeOS' },
  { id: 'generic', name: 'Other / Generic network device' },
];

// Netmiko identifiers for read-only live troubleshooting. These are kept
// separate from offline parsing because live support depends on device drivers.
export const LIVE_DEVICE_TYPES = [
  { id: 'cisco_ios', name: 'Cisco IOS / IOS-XE' },
  { id: 'cisco_nxos', name: 'Cisco NX-OS' },
  { id: 'cisco_asa', name: 'Cisco ASA' },
  { id: 'arista_eos', name: 'Arista EOS' },
  { id: 'juniper_junos', name: 'Juniper Junos' },
  { id: 'aruba_aoscx', name: 'Aruba AOS-CX' },
  { id: 'hp_procurve', name: 'Aruba / HP ProCurve' },
  { id: 'hp_comware', name: 'HPE Comware' },
  { id: 'extreme_exos', name: 'ExtremeXOS' },
  { id: 'ruckus_fastiron', name: 'Ruckus FastIron / ICX' },
  { id: 'dell_os10', name: 'Dell OS10' },
  { id: 'dell_force10', name: 'Dell Force10 / OS9' },
  { id: 'mikrotik_routeros', name: 'MikroTik RouterOS' },
  { id: 'vyos', name: 'VyOS' },
  { id: 'fortinet', name: 'Fortinet FortiOS' },
  { id: 'paloalto_panos', name: 'Palo Alto PAN-OS' },
  { id: 'ubiquiti_edge', name: 'Ubiquiti EdgeOS' },
  { id: 'linux', name: 'Linux server / host (SSH)' },
];
